---
abstract: 'DEPRECATED -- Provides a convenient method for exporting a 2D piddle.'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-IO-Export2D
requires:
  Carp: 0
  PDL::Util: 0
  perl: 5.006000
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jberger/PDL-IO-Export2D/issues
  homepage: http://search.cpan.org/perldoc?PDL::IO::Export2D
  repository: git://github.com/jberger/PDL-IO-Export2D.git
version: 0.040
