---
abstract: 'Provides a convenient method for exporting a 2D piddle.'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-IO-Export2D
requires:
  Carp: 0
  PDL: 0
  Scalar::Util: 0
  perl: 5.006000
version: 0.030
